version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: bp_db_symfony
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - 3306:3306   
        networks:
            - tutorial

    # Symfony apache project container
    www:
        build: docker/php
        container_name: tutorial_symfony
        ports:
          - "8741:443"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - tutorial

    #mailhog        
    mailhog:
        image: druidfi/mailhog:latest
        restart: always
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - tutorial

    # RabbitMQ container
    rabbitmq:
        image: "rabbitmq:management"
        container_name: tutorial_rabbitmq
        ports:
            - "15672:15672" # RabbitMQ Management UI
            - "5672:5672"   # RabbitMQ Default Port
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        networks:
            - tutorial

networks:
    tutorial:

volumes:
    db-data:
    rabbitmq-data: