version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:latest
    environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailhog:
    image: druidfi/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - tutorial  
            
###< symfony/mailer ###
